/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_jnitoast_MainActivity */

#ifndef _Included_com_example_jnitoast_MainActivity
#define _Included_com_example_jnitoast_MainActivity
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_jnitoast_MainActivity
 * Method:    displayToast
 * Signature: (Ljava/lang/CharSequence;I)V
 */
JNIEXPORT void JNICALL Java_com_example_jnitoast_MainActivity_displayToast
  (JNIEnv *, jobject, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
