/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class Main */

#ifndef _Included_Main
#define _Included_Main
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     Main
 * Method:    printHelloWorld
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_Main_printHelloWorld
  (JNIEnv *, jobject);

/*
 * Class:     Main
 * Method:    getHelloWorld
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_Main_getHelloWorld
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
