/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_logtest_MainActivity */

#ifndef _Included_com_example_logtest_MainActivity
#define _Included_com_example_logtest_MainActivity
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_logtest_MainActivity
 * Method:    printLog
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_example_logtest_MainActivity_printLog
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
