/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_androidbitmap1_MainActivity */

#ifndef _Included_com_example_androidbitmap1_MainActivity
#define _Included_com_example_androidbitmap1_MainActivity
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_androidbitmap1_MainActivity
 * Method:    reverseImage
 * Signature: (Landroid/graphics/Bitmap;)V
 */
JNIEXPORT void JNICALL Java_com_example_androidbitmap1_MainActivity_reverseImage
  (JNIEnv *, jobject, jobject);

#ifdef __cplusplus
}
#endif
#endif
