/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_hellowjni_HelloJNIActivity */

#ifndef _Included_com_example_hellowjni_HelloJNIActivity
#define _Included_com_example_hellowjni_HelloJNIActivity
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_hellowjni_HelloJNIActivity
 * Method:    getHelloWorld
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_example_hellowjni_HelloJNIActivity_getHelloWorld
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
