/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class Type */

#ifndef _Included_Type
#define _Included_Type
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     Type
 * Method:    printInt
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_Type_printInt
  (JNIEnv *, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
