/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class Calc */

#ifndef _Included_Calc
#define _Included_Calc
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     Calc
 * Method:    add
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_Calc_add
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     Calc
 * Method:    sub
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_Calc_sub
  (JNIEnv *, jobject, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
