/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_brightness_MainActivity */

#ifndef _Included_com_example_brightness_MainActivity
#define _Included_com_example_brightness_MainActivity
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_brightness_MainActivity
 * Method:    brightness
 * Signature: (Landroid/graphics/Bitmap;F)V
 */
JNIEXPORT void JNICALL Java_com_example_brightness_MainActivity_brightness
  (JNIEnv *, jobject, jobject, jfloat);

#ifdef __cplusplus
}
#endif
#endif
