/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_myvoicerecoder_MainActivity */

#ifndef _Included_com_example_myvoicerecoder_MainActivity
#define _Included_com_example_myvoicerecoder_MainActivity
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_myvoicerecoder_MainActivity
 * Method:    createEngine
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_example_myvoicerecoder_MainActivity_createEngine
  (JNIEnv *, jclass);

/*
 * Class:     com_example_myvoicerecoder_MainActivity
 * Method:    createBufferQueueAudioPlayer
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_example_myvoicerecoder_MainActivity_createBufferQueueAudioPlayer
  (JNIEnv *, jclass);

/*
 * Class:     com_example_myvoicerecoder_MainActivity
 * Method:    createAudioRecorder
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_com_example_myvoicerecoder_MainActivity_createAudioRecorder
  (JNIEnv *, jclass);

/*
 * Class:     com_example_myvoicerecoder_MainActivity
 * Method:    startRecording
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_example_myvoicerecoder_MainActivity_startRecording
  (JNIEnv *, jclass);

/*
 * Class:     com_example_myvoicerecoder_MainActivity
 * Method:    setPlaying
 * Signature: (Z)Z
 */
JNIEXPORT jboolean JNICALL Java_com_example_myvoicerecoder_MainActivity_setPlaying
  (JNIEnv *, jclass, jboolean);

/*
 * Class:     com_example_myvoicerecoder_MainActivity
 * Method:    shutdown
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_example_myvoicerecoder_MainActivity_shutdown
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
