/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class Array */

#ifndef _Included_Array
#define _Included_Array
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     Array
 * Method:    printIntArr
 * Signature: ([I)V
 */
JNIEXPORT void JNICALL Java_Array_printIntArr
  (JNIEnv *, jobject, jintArray);

/*
 * Class:     Array
 * Method:    getIntArrSum
 * Signature: ([I)I
 */
JNIEXPORT jint JNICALL Java_Array_getIntArrSum
  (JNIEnv *, jobject, jintArray);

/*
 * Class:     Array
 * Method:    printCharArr
 * Signature: ([C)V
 */
JNIEXPORT void JNICALL Java_Array_printCharArr
  (JNIEnv *, jobject, jcharArray);

#ifdef __cplusplus
}
#endif
#endif
