/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_mysoundplayer_MainActivity */

#ifndef _Included_com_example_mysoundplayer_MainActivity
#define _Included_com_example_mysoundplayer_MainActivity
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_mysoundplayer_MainActivity
 * Method:    createEngine
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_example_mysoundplayer_MainActivity_createEngine
  (JNIEnv *, jclass);

/*
 * Class:     com_example_mysoundplayer_MainActivity
 * Method:    createAssetAudioPlayer
 * Signature: (Landroid/content/res/AssetManager;Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_com_example_mysoundplayer_MainActivity_createAssetAudioPlayer
  (JNIEnv *, jclass, jobject, jstring);

/*
 * Class:     com_example_mysoundplayer_MainActivity
 * Method:    setPlayingAssetAudioPlayer
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_com_example_mysoundplayer_MainActivity_setPlayingAssetAudioPlayer
  (JNIEnv *, jclass, jboolean);

/*
 * Class:     com_example_mysoundplayer_MainActivity
 * Method:    stopAssetAudioPlayer
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_example_mysoundplayer_MainActivity_stopAssetAudioPlayer
  (JNIEnv *, jclass);

/*
 * Class:     com_example_mysoundplayer_MainActivity
 * Method:    shutdown
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_example_mysoundplayer_MainActivity_shutdown
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
